"""
Weather blueprint routes — AI-powered weather advisories and travel safety.

All weather data is generated by real Gemini API calls — no hardcoded
or mock data is served to users. Responses are cached for 5 minutes
to balance freshness with API efficiency.
"""

import logging
from typing import Any

from flask import Response, jsonify

from app.blueprints.weather import weather_bp
from app.services.weather_service import get_current_weather, get_travel_advisory
from app.utils.validators import ValidationError, validate_location

logger = logging.getLogger(__name__)


@weather_bp.route("/advisory/<location>", methods=["GET"])
def weather_advisory(location: str) -> tuple[Response, int]:
    """
    Get AI-generated monsoon weather advisory for a location.

    Uses Google Gemini to produce a realistic, location-aware weather
    assessment including temperature, rainfall, wind, and risk level.

    Args:
        location: City name from the URL path.

    Returns:
        JSON response with AI-generated weather data and risk assessment.
    """
    try:
        clean_location: str = validate_location(location)
    except ValidationError as exc:
        return jsonify({"error": exc.message, "field": exc.field}), 400

    try:
        weather_data: dict[str, Any] = get_current_weather(clean_location)
        return jsonify({"status": "success", "data": weather_data}), 200
    except Exception as exc:
        logger.error("Weather advisory error for '%s': %s", location, exc)
        return jsonify({"error": "Failed to generate weather advisory."}), 503


@weather_bp.route("/travel/<origin>/<destination>", methods=["GET"])
def travel_advisory(origin: str, destination: str) -> tuple[Response, int]:
    """
    Get AI-generated travel advisory between two locations.

    Uses Google Gemini to assess route-specific monsoon risks including
    waterlogging, landslides, and road conditions.

    Args:
        origin: Starting city from the URL path.
        destination: Destination city from the URL path.

    Returns:
        JSON response with AI-generated travel risk assessment.
    """
    try:
        clean_origin: str = validate_location(origin)
        clean_destination: str = validate_location(destination)
    except ValidationError as exc:
        return jsonify({"error": exc.message, "field": exc.field}), 400

    try:
        advisory: dict[str, Any] = get_travel_advisory(clean_origin, clean_destination)
        return jsonify({"status": "success", "data": advisory}), 200
    except Exception as exc:
        logger.error(
            "Travel advisory error for '%s' -> '%s': %s",
            origin,
            destination,
            exc,
        )
        return jsonify({"error": "Failed to generate travel advisory."}), 503
